import './js/main_page/header';
import './js/main_page/hero-slider';
import './js/main_page/services';
import './js/main_page/reviews-slider';
import './js/main_page/footer';
import './js/main_page/modal-service-appointment';
import './js/main_page/up-button';
import './js/main_page/up-button';
import './js/contacts_page/modal_agreement';
